name = "cuza-worker"

account_id = "f23d89f989b552da46a4049cb843423d"
workers_dev = true
compatibility_date = "2025-10-04"
main = "src/index.ts"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 100
period = 60

# R2 Bucket Bindings
[[r2_buckets]]
binding = "FILES"
bucket_name = "cuza-bucket"
preview_bucket_name = "cuza-bucket"
remote = true

[[routes]]
pattern = "api.my-lab.ro"
custom_domain = true

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[observability.traces]
enabled = false
head_sampling_rate = 1