name: Fetch BAC 2025 Calendar

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
        node-version: '20'

      - name: Install PDF tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends poppler-utils

      - name: Download BAC calendar PDF
        run: |
          mkdir -p tmp
          curl -L --fail --retry 3 --retry-delay 2 \
          -o tmp/Calendar_bacalaureat_2025.pdf \
          "https://bacalaureat.edu.ro/Info/Calendar_bacalaureat_2025.pdf"

      - name: Convert PDF to text
        run: |
          pdftotext -enc UTF-8 -eol unix tmp/Calendar_bacalaureat_2025.pdf tmp/Calendar_bacalaureat_2025.txt
          test -s tmp/Calendar_bacalaureat_2025.txt

      - name: Parse text and produce JSON
        run: |
          node - <<'NODE'
          const fs = require('fs');

          const inPath = 'tmp/Calendar_bacalaureat_2025.txt';
          const outDir = 'public/assets/data';
          const outPath = `${outDir}/bac-calendar-2025.json`;

          const months = {
          'ianuarie': '01', 'februarie': '02', 'martie': '03', 'aprilie': '04', 'mai': '05',
          'iunie': '06', 'iulie': '07', 'august': '08', 'septembrie': '09', 'octombrie': '10',
          'noiembrie': '11', 'decembrie': '12'
          };

          const raw = fs.readFileSync(inPath, 'utf8');
          // Normalize dashes and whitespace for robust regex matching
          const text = raw
          .replace(/\r/g, '')
          .replace(/[—–‑]/g, '-') // unify em/en/nb dashes to '-'
          .replace(/\u00a0/g, ' ') // non-breaking space
          .replace(/[\t]+/g, ' ')
          .replace(/[ ]{2,}/g, ' ');

          function sliceBetween(src, startRe, endRe) {
          const s = src.search(startRe);
          if (s === -1) return '';
          const rest = src.slice(s);
          const eIdx = rest.search(endRe);
          if (eIdx === -1) return rest;
          return rest.slice(0, eIdx);
          }

          function extractSession(block, sessionName) {
          const re = /(\d{1,2})\s+(ianuarie|februarie|martie|aprilie|mai|iunie|iulie|august|septembrie|octombrie|noiembrie|decembrie)\s+(\d{4})[^\n]{0,140}?E\.(a|b|c|d)\)?/gmi;
          const dates = {};
          let m;
          while ((m = re.exec(block)) !== null) {
          const day = String(parseInt(m[1], 10)).padStart(2, '0');
          const monthNum = months[m[2].toLowerCase()];
          const year = m[3];
          const code = m[4].toLowerCase();
          if (code === 'a' || code === 'c' || code === 'd') {
          const iso = `${year}-${monthNum}-${day}`;
          dates[`E.${code}`] = iso;
          }
          }
          return { session: sessionName, dates };
          }

          // Find session blocks
          const juneBlock = sliceBetween(text, /Sesiunea\s+iunie\s+2025/i, /Sesiunea\s+iulie/i);
          const julAugBlock = sliceBetween(text, /Sesiunea\s+iulie[^\n]*2025/i, /(ANEXA|NOTA|CALENDARUL\s+privind|$)/i);

          const result = {
          year: 2025,
          sessions: [
          extractSession(juneBlock, 'iunie'),
          extractSession(julAugBlock, 'iulie-august')
          ]
          };

          fs.mkdirSync(outDir, { recursive: true });
          fs.writeFileSync(outPath, JSON.stringify(result, null, 2), 'utf8');
          console.log(`Wrote ${outPath}`);
          NODE

      - name: Commit and push JSON
        env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          if git diff --quiet -- public/assets/data/bac-calendar-2025.json; then
          echo "No changes to commit."
          exit 0
          fi
          git add public/assets/data/bac-calendar-2025.json
          git commit -m "chore(data): update BAC 2025 calendar E.a/E.c/E.d dates from official PDF"
          git push
